"""Initial schema including scheduling

Revision ID: 73396720dcd4
Revises: 
Create Date: 2026-07-16 12:51:31.615902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73396720dcd4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('actor_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_settings_key'), 'hospital_settings', ['key'], unique=True)
    op.create_table('lab_tests',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('normal_range', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_tests_category'), 'lab_tests', ['category'], unique=False)
    op.create_index(op.f('ix_lab_tests_name'), 'lab_tests', ['name'], unique=True)
    op.create_index(op.f('ix_lab_tests_status'), 'lab_tests', ['status'], unique=False)
    op.create_table('medicines',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_category'), 'medicines', ['category'], unique=False)
    op.create_index(op.f('ix_medicines_name'), 'medicines', ['name'], unique=True)
    op.create_index(op.f('ix_medicines_status'), 'medicines', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_role', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_index(op.f('ix_permissions_status'), 'permissions', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_status'), 'roles', ['status'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('pending_orders', sa.Integer(), nullable=False),
    sa.Column('next_delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_delivery_status'), 'suppliers', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    op.create_index(op.f('ix_suppliers_status'), 'suppliers', ['status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_by_id'), 'users', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('head_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_created_by_id'), 'departments', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_index(op.f('ix_departments_status'), 'departments', ['status'], unique=False)
    op.create_index(op.f('ix_departments_updated_by_id'), 'departments', ['updated_by_id'], unique=False)
    op.create_table('inventory',
    sa.Column('batch_no', sa.String(length=50), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_id', 'batch_no', name='uq_inventory_medicine_batch')
    )
    op.create_index(op.f('ix_inventory_batch_no'), 'inventory', ['batch_no'], unique=False)
    op.create_index(op.f('ix_inventory_created_by_id'), 'inventory', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_inventory_expiry_date'), 'inventory', ['expiry_date'], unique=False)
    op.create_index('ix_inventory_expiry_status', 'inventory', ['expiry_date', 'status'], unique=False)
    op.create_index(op.f('ix_inventory_medicine_id'), 'inventory', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_inventory_status'), 'inventory', ['status'], unique=False)
    op.create_index(op.f('ix_inventory_supplier_id'), 'inventory', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_inventory_updated_by_id'), 'inventory', ['updated_by_id'], unique=False)
    op.create_table('leaves',
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaves_created_by_id'), 'leaves', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_leaves_status'), 'leaves', ['status'], unique=False)
    op.create_index(op.f('ix_leaves_updated_by_id'), 'leaves', ['updated_by_id'], unique=False)
    op.create_index(op.f('ix_leaves_user_id'), 'leaves', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('uhid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('alt_mobile', sa.String(length=20), nullable=True),
    sa.Column('aadhaar', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('guardian', sa.String(length=100), nullable=True),
    sa.Column('guardian_relation', sa.String(length=50), nullable=True),
    sa.Column('scheme', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.String(length=20), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('chronic_conditions', sa.JSON(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_aadhaar'), 'patients', ['aadhaar'], unique=True)
    op.create_index(op.f('ix_patients_created_by_id'), 'patients', ['created_by_id'], unique=False)
    op.create_index('ix_patients_district_state', 'patients', ['district', 'state'], unique=False)
    op.create_index(op.f('ix_patients_mobile'), 'patients', ['mobile'], unique=False)
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_index(op.f('ix_patients_scheme'), 'patients', ['scheme'], unique=False)
    op.create_index(op.f('ix_patients_status'), 'patients', ['status'], unique=False)
    op.create_index(op.f('ix_patients_uhid'), 'patients', ['uhid'], unique=True)
    op.create_index(op.f('ix_patients_updated_by_id'), 'patients', ['updated_by_id'], unique=False)
    op.create_table('resources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_created_by_id'), 'resources', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_resources_name'), 'resources', ['name'], unique=True)
    op.create_index(op.f('ix_resources_status'), 'resources', ['status'], unique=False)
    op.create_index(op.f('ix_resources_updated_by_id'), 'resources', ['updated_by_id'], unique=False)
    op.create_table('shifts',
    sa.Column('shift_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_created_by_id'), 'shifts', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_shifts_date'), 'shifts', ['date'], unique=False)
    op.create_index(op.f('ix_shifts_status'), 'shifts', ['status'], unique=False)
    op.create_index(op.f('ix_shifts_updated_by_id'), 'shifts', ['updated_by_id'], unique=False)
    op.create_index(op.f('ix_shifts_user_id'), 'shifts', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_status'), 'user_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('bills',
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_bill_date'), 'bills', ['bill_date'], unique=False)
    op.create_index(op.f('ix_bills_created_by_id'), 'bills', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_bills_invoice_no'), 'bills', ['invoice_no'], unique=True)
    op.create_index(op.f('ix_bills_patient_id'), 'bills', ['patient_id'], unique=False)
    op.create_index(op.f('ix_bills_status'), 'bills', ['status'], unique=False)
    op.create_index(op.f('ix_bills_updated_by_id'), 'bills', ['updated_by_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_cases',
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=255), nullable=False),
    sa.Column('triage', sa.String(length=50), nullable=False),
    sa.Column('case_status', sa.String(length=50), nullable=False),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_cases_admitted_at'), 'emergency_cases', ['admitted_at'], unique=False)
    op.create_index(op.f('ix_emergency_cases_case_status'), 'emergency_cases', ['case_status'], unique=False)
    op.create_index(op.f('ix_emergency_cases_created_by_id'), 'emergency_cases', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_emergency_cases_patient_id'), 'emergency_cases', ['patient_id'], unique=False)
    op.create_index(op.f('ix_emergency_cases_patient_name'), 'emergency_cases', ['patient_name'], unique=False)
    op.create_index(op.f('ix_emergency_cases_status'), 'emergency_cases', ['status'], unique=False)
    op.create_index(op.f('ix_emergency_cases_triage'), 'emergency_cases', ['triage'], unique=False)
    op.create_index(op.f('ix_emergency_cases_updated_by_id'), 'emergency_cases', ['updated_by_id'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_created_by_id'), 'emergency_contacts', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_patient_id'), 'emergency_contacts', ['patient_id'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_status'), 'emergency_contacts', ['status'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_updated_by_id'), 'emergency_contacts', ['updated_by_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_created_by_id'), 'inventory_transactions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_inventory_id'), 'inventory_transactions', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_reference_id'), 'inventory_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_status'), 'inventory_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_transaction_type'), 'inventory_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_updated_by_id'), 'inventory_transactions', ['updated_by_id'], unique=False)
    op.create_table('medical_history',
    sa.Column('condition', sa.String(length=150), nullable=False),
    sa.Column('diagnosis_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_history_condition'), 'medical_history', ['condition'], unique=False)
    op.create_index(op.f('ix_medical_history_created_by_id'), 'medical_history', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_medical_history_patient_id'), 'medical_history', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_history_status'), 'medical_history', ['status'], unique=False)
    op.create_index(op.f('ix_medical_history_updated_by_id'), 'medical_history', ['updated_by_id'], unique=False)
    op.create_table('staff_profiles',
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_profiles_created_by_id'), 'staff_profiles', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_staff_profiles_department_id'), 'staff_profiles', ['department_id'], unique=False)
    op.create_index(op.f('ix_staff_profiles_employee_id'), 'staff_profiles', ['employee_id'], unique=True)
    op.create_index(op.f('ix_staff_profiles_status'), 'staff_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_staff_profiles_updated_by_id'), 'staff_profiles', ['updated_by_id'], unique=False)
    op.create_index(op.f('ix_staff_profiles_user_id'), 'staff_profiles', ['user_id'], unique=True)
    op.create_table('timeline_events',
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_created_by_id'), 'timeline_events', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_event_date'), 'timeline_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_timeline_events_event_type'), 'timeline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_timeline_events_patient_id'), 'timeline_events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_status'), 'timeline_events', ['status'], unique=False)
    op.create_index(op.f('ix_timeline_events_updated_by_id'), 'timeline_events', ['updated_by_id'], unique=False)
    op.create_table('bill_items',
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_items_bill_id'), 'bill_items', ['bill_id'], unique=False)
    op.create_index(op.f('ix_bill_items_created_by_id'), 'bill_items', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_bill_items_status'), 'bill_items', ['status'], unique=False)
    op.create_index(op.f('ix_bill_items_updated_by_id'), 'bill_items', ['updated_by_id'], unique=False)
    op.create_table('doctors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('qualification', sa.String(length=100), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('staff_profile_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_profile_id'], ['staff_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_created_by_id'), 'doctors', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_doctors_department_id'), 'doctors', ['department_id'], unique=False)
    op.create_index(op.f('ix_doctors_name'), 'doctors', ['name'], unique=False)
    op.create_index(op.f('ix_doctors_staff_profile_id'), 'doctors', ['staff_profile_id'], unique=True)
    op.create_index(op.f('ix_doctors_status'), 'doctors', ['status'], unique=False)
    op.create_index(op.f('ix_doctors_updated_by_id'), 'doctors', ['updated_by_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_transaction_ref'), 'payments', ['transaction_ref'], unique=True)
    op.create_table('appointments',
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=50), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('symptoms', sa.String(length=255), nullable=True),
    sa.Column('triage', sa.String(length=100), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_created_by_id'), 'appointments', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_appointments_date'), 'appointments', ['date'], unique=False)
    op.create_index('ix_appointments_date_doctor', 'appointments', ['date', 'doctor_id'], unique=False)
    op.create_index('ix_appointments_date_status', 'appointments', ['date', 'status'], unique=False)
    op.create_index(op.f('ix_appointments_department_id'), 'appointments', ['department_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_priority'), 'appointments', ['priority'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_token'), 'appointments', ['token'], unique=False)
    op.create_index(op.f('ix_appointments_updated_by_id'), 'appointments', ['updated_by_id'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_schedules_created_by_id'), 'doctor_schedules', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_doctor_schedules_doctor_id'), 'doctor_schedules', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_schedules_status'), 'doctor_schedules', ['status'], unique=False)
    op.create_index(op.f('ix_doctor_schedules_updated_by_id'), 'doctor_schedules', ['updated_by_id'], unique=False)
    op.create_table('lab_orders',
    sa.Column('sample_id', sa.String(length=50), nullable=False),
    sa.Column('sample_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('collector_name', sa.String(length=100), nullable=True),
    sa.Column('collection_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['lab_tests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_orders_created_by_id'), 'lab_orders', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_doctor_id'), 'lab_orders', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_patient_id'), 'lab_orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_priority'), 'lab_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_lab_orders_sample_id'), 'lab_orders', ['sample_id'], unique=True)
    op.create_index(op.f('ix_lab_orders_status'), 'lab_orders', ['status'], unique=False)
    op.create_index('ix_lab_orders_status_priority', 'lab_orders', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_lab_orders_test_id'), 'lab_orders', ['test_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_updated_by_id'), 'lab_orders', ['updated_by_id'], unique=False)
    op.create_table('vaccinations',
    sa.Column('vaccine_name', sa.String(length=150), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('administered_by_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('administered_by_doctor_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['administered_by_doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccinations_administered_by_doctor_id'), 'vaccinations', ['administered_by_doctor_id'], unique=False)
    op.create_index(op.f('ix_vaccinations_created_by_id'), 'vaccinations', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_vaccinations_patient_id'), 'vaccinations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_vaccinations_scheduled_date'), 'vaccinations', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_vaccinations_status'), 'vaccinations', ['status'], unique=False)
    op.create_index(op.f('ix_vaccinations_updated_by_id'), 'vaccinations', ['updated_by_id'], unique=False)
    op.create_index(op.f('ix_vaccinations_vaccine_name'), 'vaccinations', ['vaccine_name'], unique=False)
    op.create_table('consultations',
    sa.Column('diagnosis', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_appointment_id'), 'consultations', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_consultations_created_by_id'), 'consultations', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_consultations_status'), 'consultations', ['status'], unique=False)
    op.create_index(op.f('ix_consultations_updated_by_id'), 'consultations', ['updated_by_id'], unique=False)
    op.create_table('lab_reports',
    sa.Column('result_value', sa.String(length=255), nullable=False),
    sa.Column('normal_range', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('technician_name', sa.String(length=100), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('critical_finding', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['lab_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_reports_created_by_id'), 'lab_reports', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_lab_reports_is_critical'), 'lab_reports', ['is_critical'], unique=False)
    op.create_index(op.f('ix_lab_reports_order_id'), 'lab_reports', ['order_id'], unique=False)
    op.create_index(op.f('ix_lab_reports_status'), 'lab_reports', ['status'], unique=False)
    op.create_index(op.f('ix_lab_reports_updated_by_id'), 'lab_reports', ['updated_by_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_code'), 'diagnoses', ['code'], unique=False)
    op.create_index(op.f('ix_diagnoses_consultation_id'), 'diagnoses', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_created_by_id'), 'diagnoses', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_status'), 'diagnoses', ['status'], unique=False)
    op.create_index(op.f('ix_diagnoses_updated_by_id'), 'diagnoses', ['updated_by_id'], unique=False)
    op.create_table('medical_records',
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('diagnosis', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('consultation_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_records_consultation_id'), 'medical_records', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_medical_records_created_by_id'), 'medical_records', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_medical_records_doctor_id'), 'medical_records', ['doctor_id'], unique=False)
    op.create_index('ix_medical_records_patient_date', 'medical_records', ['patient_id', 'record_date'], unique=False)
    op.create_index(op.f('ix_medical_records_patient_id'), 'medical_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_records_record_date'), 'medical_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_medical_records_record_type'), 'medical_records', ['record_type'], unique=False)
    op.create_index(op.f('ix_medical_records_status'), 'medical_records', ['status'], unique=False)
    op.create_index(op.f('ix_medical_records_updated_by_id'), 'medical_records', ['updated_by_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('diagnosis', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('allergies_snapshot', sa.String(length=255), nullable=True),
    sa.Column('weight_snapshot', sa.String(length=20), nullable=True),
    sa.Column('blood_group_snapshot', sa.String(length=10), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_consultation_id'), 'prescriptions', ['consultation_id'], unique=True)
    op.create_index(op.f('ix_prescriptions_created_by_id'), 'prescriptions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_priority'), 'prescriptions', ['priority'], unique=False)
    op.create_index(op.f('ix_prescriptions_status'), 'prescriptions', ['status'], unique=False)
    op.create_index(op.f('ix_prescriptions_updated_by_id'), 'prescriptions', ['updated_by_id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('strength', sa.String(length=50), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('qty_needed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_items_created_by_id'), 'prescription_items', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_prescription_items_medicine_id'), 'prescription_items', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_prescription_items_status'), 'prescription_items', ['status'], unique=False)
    op.create_index(op.f('ix_prescription_items_updated_by_id'), 'prescription_items', ['updated_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_items_updated_by_id'), table_name='prescription_items')
    op.drop_index(op.f('ix_prescription_items_status'), table_name='prescription_items')
    op.drop_index(op.f('ix_prescription_items_prescription_id'), table_name='prescription_items')
    op.drop_index(op.f('ix_prescription_items_medicine_id'), table_name='prescription_items')
    op.drop_index(op.f('ix_prescription_items_created_by_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_prescriptions_updated_by_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_status'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_priority'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_created_by_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_consultation_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_medical_records_updated_by_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_status'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_record_type'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_record_date'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_patient_id'), table_name='medical_records')
    op.drop_index('ix_medical_records_patient_date', table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_doctor_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_created_by_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_consultation_id'), table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_diagnoses_updated_by_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_status'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_created_by_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_consultation_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_code'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_lab_reports_updated_by_id'), table_name='lab_reports')
    op.drop_index(op.f('ix_lab_reports_status'), table_name='lab_reports')
    op.drop_index(op.f('ix_lab_reports_order_id'), table_name='lab_reports')
    op.drop_index(op.f('ix_lab_reports_is_critical'), table_name='lab_reports')
    op.drop_index(op.f('ix_lab_reports_created_by_id'), table_name='lab_reports')
    op.drop_table('lab_reports')
    op.drop_index(op.f('ix_consultations_updated_by_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_status'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_created_by_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_appointment_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_vaccinations_vaccine_name'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_updated_by_id'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_status'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_scheduled_date'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_patient_id'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_created_by_id'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_administered_by_doctor_id'), table_name='vaccinations')
    op.drop_table('vaccinations')
    op.drop_index(op.f('ix_lab_orders_updated_by_id'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_test_id'), table_name='lab_orders')
    op.drop_index('ix_lab_orders_status_priority', table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_status'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_sample_id'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_priority'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_patient_id'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_doctor_id'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_created_by_id'), table_name='lab_orders')
    op.drop_table('lab_orders')
    op.drop_index(op.f('ix_doctor_schedules_updated_by_id'), table_name='doctor_schedules')
    op.drop_index(op.f('ix_doctor_schedules_status'), table_name='doctor_schedules')
    op.drop_index(op.f('ix_doctor_schedules_doctor_id'), table_name='doctor_schedules')
    op.drop_index(op.f('ix_doctor_schedules_created_by_id'), table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    op.drop_index(op.f('ix_appointments_updated_by_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_token'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_priority'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_department_id'), table_name='appointments')
    op.drop_index('ix_appointments_date_status', table_name='appointments')
    op.drop_index('ix_appointments_date_doctor', table_name='appointments')
    op.drop_index(op.f('ix_appointments_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_created_by_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_payments_transaction_ref'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_doctors_updated_by_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_status'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_staff_profile_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_name'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_department_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_created_by_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_bill_items_updated_by_id'), table_name='bill_items')
    op.drop_index(op.f('ix_bill_items_status'), table_name='bill_items')
    op.drop_index(op.f('ix_bill_items_created_by_id'), table_name='bill_items')
    op.drop_index(op.f('ix_bill_items_bill_id'), table_name='bill_items')
    op.drop_table('bill_items')
    op.drop_index(op.f('ix_timeline_events_updated_by_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_status'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_patient_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_event_type'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_event_date'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_created_by_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_staff_profiles_user_id'), table_name='staff_profiles')
    op.drop_index(op.f('ix_staff_profiles_updated_by_id'), table_name='staff_profiles')
    op.drop_index(op.f('ix_staff_profiles_status'), table_name='staff_profiles')
    op.drop_index(op.f('ix_staff_profiles_employee_id'), table_name='staff_profiles')
    op.drop_index(op.f('ix_staff_profiles_department_id'), table_name='staff_profiles')
    op.drop_index(op.f('ix_staff_profiles_created_by_id'), table_name='staff_profiles')
    op.drop_table('staff_profiles')
    op.drop_index(op.f('ix_medical_history_updated_by_id'), table_name='medical_history')
    op.drop_index(op.f('ix_medical_history_status'), table_name='medical_history')
    op.drop_index(op.f('ix_medical_history_patient_id'), table_name='medical_history')
    op.drop_index(op.f('ix_medical_history_created_by_id'), table_name='medical_history')
    op.drop_index(op.f('ix_medical_history_condition'), table_name='medical_history')
    op.drop_table('medical_history')
    op.drop_index(op.f('ix_inventory_transactions_updated_by_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_transaction_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_status'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_reference_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_inventory_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_created_by_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_emergency_contacts_updated_by_id'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_status'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_patient_id'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_created_by_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_emergency_cases_updated_by_id'), table_name='emergency_cases')
    op.drop_index(op.f('ix_emergency_cases_triage'), table_name='emergency_cases')
    op.drop_index(op.f('ix_emergency_cases_status'), table_name='emergency_cases')
    op.drop_index(op.f('ix_emergency_cases_patient_name'), table_name='emergency_cases')
    op.drop_index(op.f('ix_emergency_cases_patient_id'), table_name='emergency_cases')
    op.drop_index(op.f('ix_emergency_cases_created_by_id'), table_name='emergency_cases')
    op.drop_index(op.f('ix_emergency_cases_case_status'), table_name='emergency_cases')
    op.drop_index(op.f('ix_emergency_cases_admitted_at'), table_name='emergency_cases')
    op.drop_table('emergency_cases')
    op.drop_table('documents')
    op.drop_index(op.f('ix_bills_updated_by_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_status'), table_name='bills')
    op.drop_index(op.f('ix_bills_patient_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_invoice_no'), table_name='bills')
    op.drop_index(op.f('ix_bills_created_by_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_bill_date'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_status'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_shifts_user_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_updated_by_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_status'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_date'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_created_by_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_resources_updated_by_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_name'), table_name='resources')
    op.drop_index(op.f('ix_resources_created_by_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_patients_updated_by_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_uhid'), table_name='patients')
    op.drop_index(op.f('ix_patients_status'), table_name='patients')
    op.drop_index(op.f('ix_patients_scheme'), table_name='patients')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_mobile'), table_name='patients')
    op.drop_index('ix_patients_district_state', table_name='patients')
    op.drop_index(op.f('ix_patients_created_by_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_aadhaar'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_leaves_user_id'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_updated_by_id'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_status'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_created_by_id'), table_name='leaves')
    op.drop_table('leaves')
    op.drop_index(op.f('ix_inventory_updated_by_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_supplier_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_status'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_medicine_id'), table_name='inventory')
    op.drop_index('ix_inventory_expiry_status', table_name='inventory')
    op.drop_index(op.f('ix_inventory_expiry_date'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_created_by_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_batch_no'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_departments_updated_by_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_status'), table_name='departments')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_created_by_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_by_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_suppliers_status'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_delivery_status'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_roles_status'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_status'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_medicines_status'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_name'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_category'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_index(op.f('ix_lab_tests_status'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_name'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_category'), table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index(op.f('ix_hospital_settings_key'), table_name='hospital_settings')
    op.drop_table('hospital_settings')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
