import type { HospitalState } from "./types";

export const initialHospitalState: HospitalState = {
  patients: [
    {
      id: "PAT-001",
      uhid: "JHR-2026-00892",
      name: "Suresh Oraon",
      gender: "Male",
      dob: "1981-05-12",
      age: 45,
      mobile: "+91 98350 12345",
      aadhaar: "XXXX-XXXX-8921",
      address: "Village Panigarha, Bharno Block",
      district: "Gumla",
      state: "Jharkhand",
      bloodGroup: "B+",
      guardian: "Late Ramesh Oraon",
      guardianRelation: "Father",
      emergencyContact: "Sunita Oraon (Wife)",
      emergencyPhone: "+91 98350 12346",
      scheme: "PM-JAY (Ayushman Bharat)",
      occupation: "Farmer",
      registeredAt: "08:15 AM",
      allergies: ["Penicillin"],
      chronicConditions: ["Hypertension"],
      weight: "68 kg",
    },
    {
      id: "PAT-002",
      uhid: "JHR-2026-00893",
      name: "Anjali Devi",
      gender: "Female",
      dob: "1998-08-20",
      age: 28,
      mobile: "+91 94311 54321",
      aadhaar: "XXXX-XXXX-4321",
      address: "Ward 4, Sisai Road, Bharno",
      district: "Gumla",
      state: "Jharkhand",
      bloodGroup: "O+",
      guardian: "Rakesh Kumar",
      guardianRelation: "Husband",
      emergencyContact: "Rakesh Kumar",
      emergencyPhone: "+91 94311 54322",
      scheme: "JSSK (Maternal Health)",
      occupation: "Homemaker",
      registeredAt: "08:30 AM",
      allergies: ["None"],
      chronicConditions: ["Pregnancy - 3rd Trimester"],
      weight: "62 kg",
    },
    {
      id: "PAT-003",
      uhid: "JHR-2026-00894",
      name: "Bipin Kujur",
      gender: "Male",
      dob: "1964-11-03",
      age: 62,
      mobile: "+91 97710 98765",
      aadhaar: "XXXX-XXXX-7654",
      address: "Borea Toli, Near CHC",
      district: "Gumla",
      state: "Jharkhand",
      bloodGroup: "A+",
      guardian: "Amit Kujur",
      guardianRelation: "Son",
      emergencyContact: "Amit Kujur",
      emergencyPhone: "+91 97710 98766",
      scheme: "State BPL Card",
      occupation: "Retired Teacher",
      registeredAt: "09:05 AM",
      allergies: ["Sulfa drugs"],
      chronicConditions: ["Type 2 Diabetes", "Asthma"],
      weight: "74 kg",
    },
    {
      id: "PAT-004",
      uhid: "JHR-2026-00895",
      name: "Meena Kumari",
      gender: "Female",
      dob: "2019-03-15",
      age: 7,
      mobile: "+91 99340 11223",
      aadhaar: "XXXX-XXXX-1122",
      address: "Amba Toli, Bharno",
      district: "Gumla",
      state: "Jharkhand",
      bloodGroup: "AB+",
      guardian: "Santosh Ram",
      guardianRelation: "Father",
      emergencyContact: "Santosh Ram",
      emergencyPhone: "+91 99340 11223",
      scheme: "RBSK (Child Health)",
      occupation: "Student",
      registeredAt: "09:20 AM",
      allergies: ["None"],
      chronicConditions: ["Recurrent Tonsillitis"],
      weight: "22 kg",
    },
    {
      id: "PAT-005",
      uhid: "JHR-2026-00896",
      name: "Rajeshwar Munda",
      gender: "Male",
      dob: "1988-01-10",
      age: 38,
      mobile: "+91 98351 99887",
      aadhaar: "XXXX-XXXX-9988",
      address: "Village Dumri, Bharno Block",
      district: "Gumla",
      state: "Jharkhand",
      bloodGroup: "O-",
      guardian: "Somra Munda",
      guardianRelation: "Father",
      emergencyContact: "Somra Munda",
      emergencyPhone: "+91 98351 99888",
      scheme: "PM-JAY (Ayushman Bharat)",
      occupation: "Carpenter",
      registeredAt: "09:45 AM",
      allergies: ["None"],
      chronicConditions: ["Lower Back Strain"],
      weight: "70 kg",
    },
  ],
  appointments: [
    {
      id: "APT-101",
      patientId: "PAT-001",
      uhid: "JHR-2026-00892",
      name: "Suresh Oraon",
      phone: "+91 98350 12345",
      gender: "Male",
      age: 45,
      date: "2026-07-13",
      timeSlot: "09:30 AM",
      department: "General Medicine",
      doctor: "Dr. Priya Sharma",
      room: "OPD 101",
      token: "T-01",
      status: "Waiting",
      priority: "Normal",
      symptoms: "High fever (102°F), body ache, chills since 3 days",
      triage: "Mild Fever",
      createdAt: "08:15 AM",
    },
    {
      id: "APT-102",
      patientId: "PAT-002",
      uhid: "JHR-2026-00893",
      name: "Anjali Devi",
      phone: "+91 94311 54321",
      gender: "Female",
      age: 28,
      date: "2026-07-13",
      timeSlot: "10:00 AM",
      department: "Maternal & Child Health",
      doctor: "Dr. Rakesh Kumar",
      room: "MCH 204",
      token: "T-02",
      status: "Waiting",
      priority: "Normal",
      symptoms: "Routine 3rd trimester ANC checkup, mild pedal edema",
      triage: "Routine ANC",
      createdAt: "08:30 AM",
    },
    {
      id: "APT-103",
      patientId: "PAT-003",
      uhid: "JHR-2026-00894",
      name: "Bipin Kujur",
      phone: "+91 97710 98765",
      gender: "Male",
      age: 62,
      date: "2026-07-13",
      timeSlot: "10:30 AM",
      department: "General Medicine",
      doctor: "Dr. Ramesh Gupta",
      room: "OPD 102",
      token: "T-03",
      status: "Waiting",
      priority: "Urgent",
      symptoms: "Severe breathless episodes, uncontrolled fasting blood sugar (240 mg/dL)",
      triage: "High BP / Sugar",
      createdAt: "09:05 AM",
    },
    {
      id: "APT-104",
      patientId: "PAT-004",
      uhid: "JHR-2026-00895",
      name: "Meena Kumari",
      phone: "+91 99340 11223",
      gender: "Female",
      age: 7,
      date: "2026-07-13",
      timeSlot: "11:00 AM",
      department: "Dental & Oral Care",
      doctor: "Dr. Vijay Oraon",
      room: "Dental 301",
      token: "T-04",
      status: "Scheduled",
      priority: "Normal",
      symptoms: "Severe dental caries in lower left molar, swelling around gum",
      triage: "Dental Pain",
      createdAt: "09:20 AM",
    },
  ],
  emergencies: [
    {
      id: "EMR-201",
      uhid: "JHR-2026-00801",
      name: "Prakash Tana Bhagat",
      condition: "Accident Trauma - Head Injury & Fracture",
      triage: "Critical (Red)",
      time: "10 mins ago",
      status: "Active",
    },
    {
      id: "EMR-202",
      uhid: "JHR-2026-00812",
      name: "Sunita Kumari",
      condition: "Severe Dehydration & Acute Diarrhea",
      triage: "Severe (Yellow)",
      time: "24 mins ago",
      status: "Stabilized",
    },
  ],
  completedConsults: [
    {
      id: "CNS-001",
      token: "T-00",
      name: "Rameshwar Sahu",
      uhid: "JHR-2026-00880",
      diagnosis: "Acute Upper Respiratory Tract Infection",
      time: "09:10 AM",
      doctor: "Dr. Priya Sharma",
      department: "General Medicine",
    },
  ],
  prescriptions: [
    {
      id: "RX-8842",
      patientId: "PAT-001",
      uhid: "JHR-2026-00892",
      name: "Suresh Oraon",
      age: 45,
      gender: "Male",
      doctor: "Dr. Priya Sharma",
      department: "General Medicine",
      date: "10 mins ago",
      priority: "Urgent",
      status: "Pending",
      diagnosis: "Acute Viral Fever with Rigors",
      allergies: "Penicillin",
      weight: "68 kg",
      bloodGroup: "B+",
      drugs: [
        { drugName: "Tab Paracetamol 650mg", dosage: "1 tab", frequency: "TDS (8 hrly)", duration: "5 days", qtyNeeded: 15 },
        { drugName: "Tab Azithromycin 500mg", dosage: "1 tab", frequency: "OD (24 hrly)", duration: "3 days", qtyNeeded: 3 },
        { drugName: "ORS Sachets (WHO formula)", dosage: "1 pack", frequency: "BD", duration: "3 days", qtyNeeded: 6 },
      ],
    },
    {
      id: "RX-8841",
      patientId: "PAT-002",
      uhid: "JHR-2026-00893",
      name: "Anjali Devi",
      age: 28,
      gender: "Female",
      doctor: "Dr. Rakesh Kumar",
      department: "Maternal & Child Health",
      date: "25 mins ago",
      priority: "Normal",
      status: "Pending",
      diagnosis: "3rd Trimester ANC - Mild Anemia",
      allergies: "None",
      weight: "62 kg",
      bloodGroup: "O+",
      drugs: [
        { drugName: "Tab Iron-Folic Acid (IFA Large)", dosage: "1 tab", frequency: "OD (Night)", duration: "30 days", qtyNeeded: 30 },
        { drugName: "Tab Calcium 500mg + D3", dosage: "1 tab", frequency: "OD (Morning)", duration: "30 days", qtyNeeded: 30 },
      ],
    },
    {
      id: "RX-8840",
      patientId: "PAT-003",
      uhid: "JHR-2026-00894",
      name: "Bipin Kujur",
      age: 62,
      gender: "Male",
      doctor: "Dr. Ramesh Gupta",
      department: "General Medicine",
      date: "45 mins ago",
      priority: "Normal",
      status: "Dispensed",
      diagnosis: "Type 2 DM with COPD Exacerbation",
      allergies: "Sulfa drugs",
      weight: "74 kg",
      bloodGroup: "A+",
      drugs: [
        { drugName: "Tab Metformin 500mg (SR)", dosage: "1 tab", frequency: "BD (Post meal)", duration: "30 days", qtyNeeded: 60 },
        { drugName: "Salbutamol Inhaler 100mcg", dosage: "2 puffs", frequency: "SOS", duration: "1 unit", qtyNeeded: 1 },
      ],
    },
  ],
  labOrders: [
    {
      id: "LAB-2026-892",
      sampleId: "LAB-2026-892",
      patientId: "PAT-001",
      uhid: "JHR-2026-00892",
      name: "Suresh Oraon",
      testName: "Malaria Antigen (Pf/Pv) & Complete Blood Count (CBC)",
      doctor: "Dr. Priya Sharma",
      collectionTime: "08:45 AM",
      priority: "Urgent",
      status: "Collected",
      sampleType: "Blood (EDTA + Serum)",
      collectorName: "Technician Vijay",
    },
    {
      id: "LAB-2026-893",
      sampleId: "LAB-2026-893",
      patientId: "PAT-002",
      uhid: "JHR-2026-00893",
      name: "Anjali Devi",
      testName: "Hemoglobin (Hb%), Routine Urine & VDRL",
      doctor: "Dr. Rakesh Kumar",
      collectionTime: "08:55 AM",
      priority: "Normal",
      status: "Testing",
      sampleType: "Blood + Urine",
      collectorName: "Technician Vijay",
    },
    {
      id: "LAB-2026-890",
      sampleId: "LAB-2026-890",
      patientId: "PAT-003",
      uhid: "JHR-2026-00894",
      name: "Bipin Kujur",
      testName: "Fasting Blood Sugar (FBS) & HbA1c",
      doctor: "Dr. Ramesh Gupta",
      collectionTime: "07:30 AM",
      priority: "Normal",
      status: "Completed",
      sampleType: "Fluoride Plasma",
      collectorName: "Technician Vijay",
      technicianName: "Dr. Arvind Munda",
      resultValue: "242 mg/dL (High)",
      normalRange: "70 - 110 mg/dL",
      remarks: "Severe Hyperglycemia reported to treating doctor.",
      completedTime: "08:20 AM",
    },
  ],
  criticalAlerts: [
    {
      id: "ALERT-1",
      patientName: "Bipin Kujur",
      testName: "Fasting Blood Sugar",
      finding: "242 mg/dL (Severely High)",
      urgency: "Immediate Action",
      time: "12m ago",
      uhid: "JHR-2026-00894",
    },
    {
      id: "ALERT-2",
      patientName: "Sumi Oraon",
      testName: "Hemoglobin (Hb%)",
      finding: "6.4 g/dL (Severe Anemia)",
      urgency: "Urgent Review",
      time: "34m ago",
      uhid: "JHR-2026-00860",
    },
  ],
  activeTests: [
    {
      id: "LAB-2026-893",
      patientName: "Anjali Devi",
      testName: "Hemoglobin & Routine Urine",
      status: "In Analyzer (Automated Hematology)",
      eta: "14 mins",
    },
  ],
  recentReports: [
    {
      id: "LAB-2026-890",
      patientName: "Bipin Kujur",
      testName: "Fasting Blood Sugar (FBS)",
      completedTime: "08:20 AM",
      status: "Verified",
      findings: "242 mg/dL (High) - Flagged",
    },
  ],
  inventory: [
    {
      id: "INV-101",
      name: "Paracetamol 650mg Tablets",
      category: "Antipyretic / Analgesic",
      batchNo: "BCH-2025-081",
      expiryDate: "2027-08-15",
      quantity: 14200,
      unit: "Strips (15s)",
      mrp: 30,
      purchasePrice: 18,
      manufacturer: "Jharkhand Medical Corporation",
      status: "Optimal",
    },
    {
      id: "INV-102",
      name: "Amoxicillin 500mg Capsules",
      category: "Antibiotic",
      batchNo: "BCH-2025-104",
      expiryDate: "2026-11-30",
      quantity: 420,
      unit: "Strips (10s)",
      mrp: 65,
      purchasePrice: 42,
      manufacturer: "JMSCL State Depot",
      status: "Low Stock",
    },
    {
      id: "INV-103",
      name: "Iron-Folic Acid (IFA Large) Tablets",
      category: "Maternal Nutrition",
      batchNo: "BCH-2026-012",
      expiryDate: "2028-02-28",
      quantity: 28500,
      unit: "Bottles (100s)",
      mrp: 0,
      purchasePrice: 12,
      manufacturer: "Govt Free Supply (NHM)",
      status: "Optimal",
    },
    {
      id: "INV-104",
      name: "Metformin 500mg SR Tablets",
      category: "Anti-Diabetic",
      batchNo: "BCH-2024-099",
      expiryDate: "2026-09-10",
      quantity: 6400,
      unit: "Strips (15s)",
      mrp: 45,
      purchasePrice: 28,
      manufacturer: "Cipla Health / Generic",
      status: "Optimal",
    },
    {
      id: "INV-105",
      name: "Azithromycin 500mg Tablets",
      category: "Antibiotic",
      batchNo: "BCH-2025-210",
      expiryDate: "2027-05-20",
      quantity: 180,
      unit: "Strips (3s)",
      mrp: 70,
      purchasePrice: 48,
      manufacturer: "JMSCL State Depot",
      status: "Low Stock",
    },
    {
      id: "INV-106",
      name: "ORS Sachets (WHO Formula)",
      category: "Electrolyte Replacement",
      batchNo: "BCH-2026-004",
      expiryDate: "2028-01-15",
      quantity: 9400,
      unit: "Packets",
      mrp: 20,
      purchasePrice: 9,
      manufacturer: "Jharkhand Medical Corporation",
      status: "Optimal",
    },
  ],
  transactions: [
    {
      id: "TX-901",
      time: "09:12 AM",
      type: "Dispense",
      refId: "RX-8840 (Bipin Kujur)",
      details: "Dispensed 60 Tab Metformin 500mg + 1 Inhaler",
    },
    {
      id: "TX-902",
      time: "08:40 AM",
      type: "Restock",
      refId: "PO-2026-014",
      details: "Received 5,000 ORS Sachets from JMSCL Gumla Depot",
    },
  ],
  suppliers: [
    {
      id: "SUP-1",
      name: "JMSCL Gumla Regional Medical Depot",
      pendingOrders: 2,
      deliveryDate: "July 16, 2026",
      status: "In Transit",
    },
    {
      id: "SUP-2",
      name: "Ranchi Surgical & Pharma Distributors",
      pendingOrders: 1,
      deliveryDate: "July 18, 2026",
      status: "Scheduled",
    },
  ],
  medicalRecords: [
    {
      id: "REC-2026-041",
      patientId: "PAT-001",
      date: "2026-07-13",
      type: "OPD Consultation",
      doctor: "Dr. Priya Sharma",
      department: "General Medicine",
      diagnosis: "Acute Viral Fever with Rigors",
      summary: "Patient presented with 102°F fever and generalized myalgia. Rapid malaria antigen negative. Prescribed antipyretics and supportive therapy.",
      status: "Active",
    },
    {
      id: "REC-2026-012",
      patientId: "PAT-001",
      date: "2026-04-18",
      type: "OPD Consultation",
      doctor: "Dr. Ramesh Gupta",
      department: "General Medicine",
      diagnosis: "Seasonal Allergic Rhinitis",
      summary: "Completed 5-day course of antihistamines. Symptoms fully resolved.",
      status: "Resolved",
    },
  ],
  bills: [
    {
      id: "BILL-2026-108",
      patientId: "PAT-001",
      invoiceNo: "INV-2026-0892",
      date: "2026-07-13",
      amount: "₹ 0 (Covered under PM-JAY)",
      status: "Paid",
      paymentMethod: "PM-JAY Ayushman Bharat Claim",
      items: [
        { name: "OPD Registration Fee", cost: 0 },
        { name: "Malaria Antigen Test + CBC", cost: 0 },
        { name: "Prescribed Medicines (Govt Supply)", cost: 0 },
      ],
    },
  ],
  vaccinations: [
    {
      id: "VAC-1",
      patientId: "PAT-001",
      name: "COVID-19 Booster (Covishield)",
      date: "2022-09-14",
      status: "Completed",
      dosage: "Dose 3 (Precautionary)",
      administeredBy: "CHC Bharno Immunization Cell",
    },
    {
      id: "VAC-2",
      patientId: "PAT-001",
      name: "Tetanus Toxoid (TT)",
      date: "2025-11-10",
      status: "Completed",
      dosage: "0.5 ml IM",
      administeredBy: "Emergency Ward CHC",
    },
  ],
  timelineEvents: [
    {
      id: "EV-1",
      patientId: "PAT-001",
      date: "Today, 08:15 AM",
      time: "08:15 AM",
      title: "OPD Registration Completed",
      subtitle: "Token #T-01 assigned for General Medicine (Dr. Priya Sharma)",
      type: "registration",
      department: "Reception",
    },
    {
      id: "EV-2",
      patientId: "PAT-001",
      date: "Today, 08:45 AM",
      time: "08:45 AM",
      title: "Laboratory Samples Collected",
      subtitle: "Blood sample collected for Malaria Antigen & CBC testing",
      type: "lab",
      department: "Laboratory",
    },
  ],
  notifications: [
    {
      id: "NOTIF-1",
      targetRole: "All",
      title: "System Synchronization Active",
      message: "Frontend Master Integration active across all CHC Bharno departments.",
      time: "Just now",
      read: false,
      type: "info",
    },
    {
      id: "NOTIF-2",
      targetRole: "doctor",
      title: "New OPD Patient Waiting",
      message: "Suresh Oraon (Token T-01) is waiting in General Medicine OPD 101.",
      time: "15 mins ago",
      read: false,
      type: "alert",
    },
  ],
  auditLogs: [
    {
      id: "AUD-001",
      timestamp: "2026-07-13 08:15:22",
      actorRole: "reception",
      actorName: "Reception Desk",
      action: "PATIENT_REGISTERED",
      entityType: "Patient",
      entityId: "PAT-001",
      description: "Registered patient Suresh Oraon (UHID: JHR-2026-00892) under PM-JAY scheme",
    },
    {
      id: "AUD-002",
      timestamp: "2026-07-13 08:45:10",
      actorRole: "lab",
      actorName: "Technician Vijay",
      action: "SAMPLE_COLLECTED",
      entityType: "LabOrder",
      entityId: "LAB-2026-892",
      description: "Collected blood sample for Malaria Antigen & CBC testing",
    },
  ],
  currentSimulatedPatientId: "PAT-001",
  isSimulationRunning: false,

  // IT Admin Initial Data
  staff: [
    {
      id: "CHC-DOC-001",
      name: "Dr. Priya Sharma",
      username: "dr.priya",
      email: "dr.priya@chcbharno.gov.in",
      passwordTemp: "WelcomeDoc@123",
      department: "General Medicine",
      designation: "Chief Medical Officer (CMO)",
      joiningDate: "2019-04-12",
      role: "doctor",
      status: "Active",
    },
    {
      id: "CHC-DOC-002",
      name: "Dr. Rakesh Kumar",
      username: "dr.rakesh",
      email: "dr.rakesh@chcbharno.gov.in",
      passwordTemp: "MchStaff@321",
      department: "Gynecology & Obstetrics",
      designation: "Senior Gynaecologist",
      joiningDate: "2020-05-18",
      role: "doctor",
      status: "Active",
    },
    {
      id: "CHC-REC-001",
      name: "Sanjay Soren",
      username: "rec.sanjay",
      email: "rec.sanjay@chcbharno.gov.in",
      passwordTemp: "BharnoFront@99",
      department: "Administration",
      designation: "Front Desk Supervisor",
      joiningDate: "2021-08-01",
      role: "reception",
      status: "Active",
    },
    {
      id: "CHC-LAB-001",
      name: "Dr. Arvind Munda",
      username: "lab.arvind",
      email: "lab.arvind@chcbharno.gov.in",
      passwordTemp: "LabTech@7788",
      department: "Pathology",
      designation: "Lab Officer",
      joiningDate: "2021-02-15",
      role: "lab",
      status: "Active",
    },
    {
      id: "CHC-PHA-001",
      name: "Kundan Gope",
      username: "pharmacy.kundan",
      email: "pharmacy.kundan@chcbharno.gov.in",
      passwordTemp: "MedsDispense@5",
      department: "Pharmacy",
      designation: "Pharmacist",
      joiningDate: "2022-10-10",
      role: "pharmacy",
      status: "Active",
    },
    {
      id: "CHC-IT-001",
      name: "Dipanshu Kumar",
      username: "admin.it",
      email: "admin@chcbharno.gov.in",
      passwordTemp: "ITSupport@4321",
      department: "Administration",
      designation: "IT Support Specialist",
      joiningDate: "2023-01-10",
      role: "it-admin",
      status: "Active",
    },
  ],
  departments: [
    { id: "DEP-MED", name: "General Medicine", headName: "Dr. Priya Sharma", staffCount: 8 },
    { id: "DEP-GYN", name: "Gynecology & Obstetrics", headName: "Dr. Rakesh Kumar", staffCount: 4 },
    { id: "DEP-PED", name: "Pediatrics", headName: "Dr. Ramesh Gupta", staffCount: 3 },
    { id: "DEP-PTH", name: "Pathology", headName: "Dr. Arvind Munda", staffCount: 3 },
    { id: "DEP-PHR", name: "Pharmacy", headName: "Kundan Gope", staffCount: 4 },
    { id: "DEP-ADM", name: "Administration", headName: "Dipanshu Kumar", staffCount: 6 },
  ],
  devices: [
    { id: "DEV-REC-01", name: "Reception Main Terminal", assignedTo: "Sanjay Soren", status: "Online", location: "Front Desk Counter 1" },
    { id: "DEV-DOC-01", name: "Doctor Consult Tablet", assignedTo: "Dr. Priya Sharma", status: "Online", location: "OPD Room 1" },
    { id: "DEV-LAB-PC", name: "Analyzer Interface PC", assignedTo: "Dr. Arvind Munda", status: "Online", location: "Pathology Lab" },
    { id: "DEV-PHA-PC", name: "Billing & Stock Terminal", assignedTo: "Kundan Gope", status: "Online", location: "Pharmacy Dispatch" },
    { id: "DEV-PRN-01", name: "Receipt & Barcode Printer", assignedTo: "Sanjay Soren", status: "Online", location: "Front Desk Counter 2" },
    { id: "DEV-BIO-01", name: "Biometric Attendance Device", assignedTo: "All Staff", status: "Online", location: "Staff Entrance" },
  ],
  itMetrics: {
    onlineUsers: 6,
    activeSessions: 8,
    serverStatus: "Healthy",
    databaseStatus: "Connected",
    storageUsedGB: 124.6,
    storageTotalGB: 512,
    backupStatus: "Success",
    failedLoginsToday: 2,
    cpuUsagePct: 18,
    memoryUsagePct: 44,
  },
  hospitalConfig: {
    hospitalName: "Community Health Centre (CHC) Bharno",
    workingHours: "08:00 AM - 02:00 PM (OPD), Emergency 24/7",
    appointmentSlotDurationMin: 15,
    governmentSchemes: ["PM-JAY Ayushman Bharat", "Jharkhand Rajya Khadya Suraksha", "JSSK (Maternal Care)", "RBSK (Child Welfare)"],
    medicineCategories: ["Antipyretic", "Antibiotic", "Analgesic", "Antihistamine", "Multivitamin", "Electrolyte"],
    labCategories: ["Hematology", "Biochemistry", "Serology", "Microbiology", "Urine Routine"],
  },
};

